--- 

- name: install personal cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - atom
    - camtasia
    - docker
    - dropbox
    - github-desktop
    - google-chrome
    - google-drive
    - java
    - microsoft-office
    - postman
    - slack
    - sonos
    - skype
    - vmware-fusion
    - zotero
- name: install personal homebrew apps
  homebrew: name={{item}} state=present
  with_items:
    - leiningen
    - vault
    - rlwrap

- name: Debugging the dock_apps var
  debug: msg="The dock_apps are {{ dock_apps }}"

- name: Debugging installed_apps var
  debug: msg="But install_apps are {{installed_apps.stdout_lines}}"
