---

computername: Upslope
git_user_name: Kenneth L. Smith
git_user_email: ken.smith@2scientists.net
osx_defaults:
  - domain: 'NSGlobalDomain'
    key: 'com.apple.swipescrolldirection'
    type: boolean
    value: false
  - domain: 'com.apple.screensaver'
    key: 'askForPassword'
    type: int
    value: 1
  - domain: 'com.apple.screensaver'
    key: 'askForPasswordDelay'
    type: float
    value: 5
  - domain: 'com.apple.dock'
    key: 'wvous-bl-corner'
    type: int
    value: 5 # Sets bottom-left corner to enable screensaver
  - domain: 'com.apple.dock'
    key: 'wvous-bl-modifier'
    type: int
    value: 0
  - domain: 'com.apple.dock'
    key: 'wvous-br-corner'
    type: int
    value: 6 # Sets bottom-right corner to disable screensaver
  - domain: 'com.apple.dock'
    key: 'wvous-br-modifier'
    type: int
    value: 0
  - domain: 'com.apple.dock'
    key: 'wvous-bl-corner'
    type: int
    value: 5
  - domain: 'com.apple.driver.AppleBluetoothMultitouch.trackpad'
    key: 'Clicking' # True to enable tap to click
    type: boolean
    value: true
  - domain: 'com.apple.menuextra.battery'
    key: 'ShowPercent'
    type: string
    value: 'YES'
atom_upgrade_all: True
atom_packages:
  - git-plus
  - ink
  - language-docker
  - proto-repl
  - proto-repl-charts
  - swackets
  - tool-bar
