---
galaxy_info:
  author: Roderik van der Veer
  description: Ansible profile role for developers
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - superlumic.superlumic-computername
  - superlumic.superlumic-cli
  - superlumic.superlumic-homebrew
  - superlumic.superlumic-php
  - superlumic.superlumic-sublimetext
  - superlumic.superlumic-node
  - superlumic.superlumic-vim
  - profile-all
