---

- src: https://github.com/superlumic/ansible-role-homebrew.git
  name: roderik.superlumic-homebrew

- src: https://github.com/superlumic/ansible-role-osx-defaults.git
  name: roderik.superlumic-osx-defaults

- src: https://github.com/superlumic/ansible-role-computername.git
  name: roderik.superlumic-computername

- src: jgkim.atom

- src: https://github.com/Ken-2scientists/ansible-role-dock-items.git
  name: danbohea.dock-items
