---

- src: https://github.com/superlumic/ansible-role-homebrew.git
  name: superlumic.superlumic-homebrew

- src: https://github.com/superlumic/ansible-role-osx-defaults.git
  name: superlumic.superlumic-osx-defaults

- src: https://github.com/superlumic/ansible-role-computername.git
  name: superlumic.superlumic-computername
