---
galaxy_info:
  author: Kenneth L. Smith
  description: Ansible profile role for my apps
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
